start-at-login = true

after-startup-command = ['exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0']

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 300
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = false

[key-mapping]
preset = 'qwerty'

[mode.main.binding]
ctrl-alt-enter = 'fullscreen'
ctrl-alt-f = 'layout floating tiling'

alt-shift-h = 'join-with left'
alt-shift-j = 'join-with down'
alt-shift-k = 'join-with up'
alt-shift-l = 'join-with right'

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

ctrl-alt-cmd-left = 'focus left'
ctrl-alt-cmd-down = 'focus down'
ctrl-alt-cmd-up = 'focus up'
ctrl-alt-cmd-right = 'focus right'

ctrl-alt-left = 'move left'
ctrl-alt-down = 'move down'
ctrl-alt-up = 'move up'
ctrl-alt-right = 'move right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'

alt-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
alt-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
alt-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
alt-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

[gaps]
inner.horizontal = 20
inner.vertical =   20
outer.left =       20
outer.bottom =     20
outer.top =        20
outer.right =      20

[[on-window-detected]]
if.app-name-regex-substring = 'zed'
run = 'fullscreen'

[[on-window-detected]]
if.app-name-regex-substring = 'safari'
run = 'fullscreen'
